# Generated by Django 6.0.5 on 2026-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(help_text='Webcam index (e.g. 0) or IP Camera RTSP/HTTP URL', max_length=255)),
                ('orientation', models.CharField(choices=[('normal', 'Normal'), ('rot90_cw', 'Rotate 90° CW'), ('rot90_ccw', 'Rotate 90° CCW'), ('flip180', 'Flip 180°')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='recognitionlog',
            name='camera_name',
            field=models.CharField(default='Default Camera', max_length=100),
        ),
    ]
