# Generated by Django 6.0.5 on 2026-06-04 11:10

from django.db import migrations

def seed_default_camera(apps, schema_editor):
    Camera = apps.get_model('app', 'Camera')
    if not Camera.objects.exists():
        Camera.objects.create(
            name="Default Webcam",
            source="0",
            orientation="normal",
            is_active=True
        )

def revert_default_camera(apps, schema_editor):
    Camera = apps.get_model('app', 'Camera')
    Camera.objects.filter(name="Default Webcam", source="0").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_camera_recognitionlog_camera_name'),
    ]

    operations = [
        migrations.RunPython(seed_default_camera, revert_default_camera),
    ]
