# Generated by Django 6.0.5 on 2026-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_seed_default_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='orientation',
            field=models.CharField(choices=[('normal', 'Normal'), ('rot90_cw', 'Rotate 90° CW'), ('rot90_ccw', 'Rotate 90° CCW'), ('flip180', 'Flip 180°'), ('mirror_h', 'Mirror Horizontally')], default='normal', max_length=20),
        ),
    ]
