# Generated by Django 6.0.5 on 2026-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_devicepushtoken_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_source',
            field=models.CharField(blank=True, choices=[('APP', 'Mobile App'), ('TELEGRAM', 'Telegram Bot')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
