# Generated by Django 6.0.5 on 2026-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_recognitionlog_detection_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_camera_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='alert_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='alert_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
