# Generated by Django 6.0.5 on 2026-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notification_alert_camera_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('OFFICE_STAFF', 'Office Member'), ('PEON', 'Peon'), ('LAB_STAFF', 'Lab Staff'), ('OTHER', 'Other')], default='STUDENT', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='class_name',
            field=models.CharField(blank=True, help_text='Class / Batch for student', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, help_text='Department / Role for staff', max_length=100, null=True),
        ),
    ]
