# Generated by Django 6.0.5 on 2026-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_person_category_person_class_name_person_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('OFFICE_STAFF', 'Office Member'), ('PEON', 'Peon'), ('LAB_STAFF', 'Lab Staff'), ('SECURITY', 'Security Staff'), ('OTHER', 'Other')], default='STUDENT', max_length=30),
        ),
    ]
