# Generated by Django 6.0.5 on 2026-10-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_security_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='security_note',
            field=models.TextField(blank=True, help_text='Security note from operator about suspicious activity', null=True),
        ),
    ]
