# Generated by Django 6.0.5 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notification_security_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionlog',
            name='status',
            field=models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown'), ('APPROVED', 'Approved')], max_length=10),
        ),
        migrations.DeleteModel(
            name='PersonEmbedding',
        ),
    ]
