# Generated by Django 6.0.5 on 2026-10-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_recognitionlog_status_delete_personembedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='status',
            field=models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown (Pending)'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='camera',
            table='camera',
        ),
        migrations.AlterModelTable(
            name='devicepushtoken',
            table='device_push_token',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='personimage',
            table='person_image',
        ),
        migrations.AlterModelTable(
            name='recognitionlog',
            table='recognition_log',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
