# Generated by Django 6.0.5 on 2026-10-03 09:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_options_alter_recognitionlog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.ImageField(upload_to=app.models.person_directory_path),
        ),
    ]
